"use client";

import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useState } from "react";

import { AdminPageHeader, AdminPanel, AsyncContentState, StatusBadge } from "@/components/admin/admin-ui";
import { httpClient } from "@/services/http-client";
import { useAuthStore } from "@/stores/auth-store";

type Role = { id: string; code: string; name: string; description?: string; permissionGrants: { permission: { code: string; name: string } }[] };
type User = { id: string; firstName: string; lastName?: string; email: string; status: "ACTIVE" | "INACTIVE" | "LOCKED"; roles: { id: string; code: string; name: string }[] };

export default function UsersPage() {
  const accessToken = useAuthStore((state) => state.accessToken); const hydrated = useAuthStore((state) => state.hydrated); const queryClient = useQueryClient();
  const [showCreate, setShowCreate] = useState(false); const [editing, setEditing] = useState<User>(); const [message, setMessage] = useState(""); const [isSaving, setIsSaving] = useState(false);
  const headers = { Authorization: `Bearer ${accessToken}` };
  const users = useQuery({ queryKey: ["users"], enabled: Boolean(accessToken) && hydrated, queryFn: async () => (await httpClient.get<User[]>("/api/admin/users", { headers })).data });
  const roles = useQuery({ queryKey: ["roles"], enabled: Boolean(accessToken) && hydrated, queryFn: async () => (await httpClient.get<Role[]>("/api/admin/roles", { headers })).data });
  async function saveUser(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const roleIds = roles.data?.filter((role) => form.get(`role-${role.id}`) === "on").map((role) => role.id) ?? []; if (!roleIds.length) { setMessage("Selecciona al menos un rol."); return; } const data = { firstName: String(form.get("firstName")), lastName: String(form.get("lastName")) || undefined, email: String(form.get("email")), ...(editing ? {} : { password: String(form.get("password")) }), roleIds }; setIsSaving(true); setMessage(""); try { if (editing) await httpClient.put(`/api/admin/users/${editing.id}`, data, { headers }); else await httpClient.post("/api/admin/users", data, { headers }); await queryClient.invalidateQueries({ queryKey: ["users"] }); setShowCreate(false); setEditing(undefined); setMessage(editing ? "Usuario actualizado." : "Usuario creado."); } catch { setMessage("No fue posible guardar el usuario. Revisa el correo, contraseña y permisos."); } finally { setIsSaving(false); } }
  async function deactivate(user: User) { if (!window.confirm(`Desactivar el acceso de ${user.firstName}?`)) return; setIsSaving(true); setMessage(""); try { await httpClient.put(`/api/admin/users/${user.id}`, { status: "INACTIVE" }, { headers }); await queryClient.invalidateQueries({ queryKey: ["users"] }); setMessage("Usuario desactivado. Sus historiales se conservaron."); } catch { setMessage("No fue posible desactivar este usuario. No puedes desactivar tu propia cuenta."); } finally { setIsSaving(false); } }
  if (!hydrated) return <main className="p-8">Restaurando sesion...</main>;
  if (!accessToken) return <main className="p-8"><h1 className="text-2xl font-bold">Equipo</h1><Link className="mt-3 inline-block underline" href="/auth/login">Inicia sesion para ver el equipo.</Link></main>;
  const form = (user?: User) => <form className="grid gap-4 p-5" onSubmit={saveUser}><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold text-[#486068]">Nombre<input className="mt-1 min-h-11 w-full border border-[#879a9e] bg-[#fffef9] px-3 text-[#172b34]" defaultValue={user?.firstName} name="firstName" required /></label><label className="text-sm font-bold text-[#486068]">Apellidos<input className="mt-1 min-h-11 w-full border border-[#879a9e] bg-[#fffef9] px-3 text-[#172b34]" defaultValue={user?.lastName} name="lastName" /></label></div><label className="text-sm font-bold text-[#486068]">Correo<input className="mt-1 min-h-11 w-full border border-[#879a9e] bg-[#fffef9] px-3 text-[#172b34]" defaultValue={user?.email} name="email" type="email" required /></label>{!user && <label className="text-sm font-bold text-[#486068]">Contraseña temporal<input className="mt-1 min-h-11 w-full border border-[#879a9e] bg-[#fffef9] px-3 text-[#172b34]" minLength={12} name="password" type="password" required /></label>}<fieldset><legend className="text-sm font-bold text-[#486068]">Roles y permisos</legend><div className="mt-2 grid gap-2">{roles.data?.map((role) => <label className="flex cursor-pointer gap-3 border border-[#bac6c7] p-3" key={role.id}><input defaultChecked={user?.roles.some((assigned) => assigned.id === role.id)} name={`role-${role.id}`} type="checkbox" /><span><strong className="block text-sm text-[#172b34]">{role.name}</strong><small className="block leading-5 text-[#486068]">{role.permissionGrants.map((grant) => grant.permission.name).join(" · ")}</small></span></label>)}</div></fieldset><div className="flex flex-wrap gap-3"><button className="min-h-11 bg-[#172b34] px-4 text-sm font-extrabold text-[#f4f3ed] disabled:opacity-50" disabled={isSaving}>{user ? "Guardar permisos" : "Crear usuario"}</button><button className="min-h-11 border border-[#879a9e] px-4 text-sm font-bold text-[#486068]" onClick={() => { setShowCreate(false); setEditing(undefined); }} type="button">Cancelar</button></div></form>;
  return <div className="p-5 md:p-8"><AdminPageHeader action={<button className="min-h-11 bg-[#172b34] px-4 text-sm font-extrabold text-[#f4f3ed]" onClick={() => { setEditing(undefined); setShowCreate(true); }}>Nuevo usuario</button>} eyebrow="Personas y accesos" title="Usuarios y permisos" description="Crea accesos, asigna roles y desactiva cuentas sin eliminar sus historiales." />{message && <p className="mt-5 border border-[#bac6c7] bg-[#fffef9] p-3 text-sm text-[#486068]" role="status">{message}</p>}{showCreate && <AdminPanel className="mt-7"><div className="border-b border-[#bac6c7] p-5"><h2 className="font-bold">Crear usuario</h2></div>{form()}</AdminPanel>}{editing && <AdminPanel className="mt-7"><div className="border-b border-[#bac6c7] p-5"><h2 className="font-bold">Editar acceso de {editing.firstName}</h2></div>{form(editing)}</AdminPanel>}<AdminPanel className="mt-7"><div className="flex items-center justify-between border-b border-[#bac6c7] p-5"><h2 className="font-bold">Miembros</h2><span className="font-[family-name:var(--font-bebas-neue)] text-2xl tabular-nums text-[#486068]">{users.data?.length ?? 0}</span></div><AsyncContentState loading={users.isLoading || roles.isLoading} error={users.isError || roles.isError} empty={!users.isLoading && !users.isError && users.data?.length === 0} emptyTitle="Aún no hay usuarios" emptyDescription="Los miembros con acceso aparecerán aquí cuando se creen."><div className="divide-y divide-[#bac6c7]">{users.data?.map((user) => <article className="grid gap-3 p-5 md:grid-cols-[3rem_1fr_auto_auto] md:items-center" key={user.id}><span className="grid size-11 place-items-center rounded-full bg-[#e8d6b3] font-bold text-[#172b34]">{user.firstName.slice(0, 1).toUpperCase()}</span><div className="min-w-0"><h3 className="font-bold text-[#172b34]">{user.firstName} {user.lastName}</h3><p className="truncate text-sm text-[#486068]" title={user.email}>{user.email}</p><p className="mt-1 text-xs font-bold text-[#486068]">{user.roles.map((role) => role.name).join(" · ") || "Sin rol"}</p></div><StatusBadge status={user.status} label={user.status === "ACTIVE" ? "Activo" : user.status === "INACTIVE" ? "Inactivo" : "Bloqueado"} /><div className="flex flex-wrap gap-2"><button className="min-h-10 border border-[#879a9e] px-3 text-sm font-bold text-[#486068]" onClick={() => { setShowCreate(false); setEditing(user); }}>Editar</button>{user.status === "ACTIVE" && <button className="min-h-10 border border-[#b94a3f] px-3 text-sm font-bold text-[#7b2d25]" disabled={isSaving} onClick={() => deactivate(user)}>Desactivar</button>}</div></article>)}</div></AsyncContentState></AdminPanel></div>;
}
