"use client";

import { FormEvent, useEffect, useState } from "react";

import { AppointmentHold, Barber, Branch, createAppointment, createAppointmentHold, createCheckoutSession, getAvailability, getBarbers, getBranches, getServices, Service } from "@/services/booking-service";

function dateValue(offset = 0) { const date = new Date(); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); }
function dateLabel(date: string) { return new Intl.DateTimeFormat("es-MX", { weekday: "short", day: "numeric", month: "short" }).format(new Date(`${date}T12:00:00`)); }
function timeLabel(value: string) { return new Intl.DateTimeFormat("es-MX", { hour: "numeric", minute: "2-digit" }).format(new Date(value)); }

export default function BookingPage() {
  const [branches, setBranches] = useState<Branch[]>([]); const [services, setServices] = useState<Service[]>([]); const [barbers, setBarbers] = useState<Barber[]>([]);
  const [branchId, setBranchId] = useState(""); const [serviceId, setServiceId] = useState(""); const [barberId, setBarberId] = useState(""); const [date, setDate] = useState(dateValue); const [slots, setSlots] = useState<{ startAt: string; endAt: string }[]>([]); const [startAt, setStartAt] = useState("");
  const [hold, setHold] = useState<AppointmentHold>(); const [appointment, setAppointment] = useState<{ id: string; confirmationCode: string }>(); const [error, setError] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false); const [isLoadingSlots, setIsLoadingSlots] = useState(false);
  useEffect(() => { getBranches().then(setBranches).catch(() => setError("No fue posible cargar las sucursales.")); }, []);
  useEffect(() => { if (branchId) getServices(branchId).then(setServices).catch(() => setError("No fue posible cargar servicios.")); }, [branchId]);
  useEffect(() => { if (branchId && serviceId) getBarbers(branchId, serviceId).then(setBarbers).catch(() => setError("No fue posible cargar barberos.")); }, [branchId, serviceId]);
  useEffect(() => { if (!branchId || !serviceId || !barberId) return; void (async () => { await Promise.resolve(); setIsLoadingSlots(true); try { setSlots((await getAvailability(branchId, serviceId, barberId, date)).slots); } catch { setSlots([]); setError("No fue posible consultar los horarios disponibles."); } finally { setIsLoadingSlots(false); } })(); }, [branchId, serviceId, barberId, date]);
  async function reserve(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!startAt) return; setError(""); setIsSubmitting(true); try { setHold(await createAppointmentHold({ branchId, serviceId, barberId, startAt })); } catch { setError("Ese horario ya no esta disponible. Elige otro horario."); } finally { setIsSubmitting(false); } }
  async function confirm(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!hold) return; setError(""); setIsSubmitting(true); const form = new FormData(event.currentTarget); try { const created = await createAppointment(hold.token, { name: String(form.get("name")), phone: String(form.get("phone")), email: String(form.get("email")) || undefined, notes: String(form.get("notes")) || undefined }); setAppointment(created); } catch { setError("No fue posible confirmar la cita. El hold puede haber expirado."); } finally { setIsSubmitting(false); } }
  async function pay() { if (!appointment) return; setIsSubmitting(true); try { window.location.assign((await createCheckoutSession(appointment.id)).checkoutUrl); } catch { setError("No fue posible iniciar el pago."); setIsSubmitting(false); } }
  if (appointment) return <main className="flex min-h-screen items-center justify-center bg-stone-950 p-6 text-stone-100"><section className="w-full max-w-lg rounded-3xl border border-emerald-500/40 bg-stone-900 p-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Cita confirmada</p><h1 className="mt-3 text-3xl font-bold">Codigo: {appointment.confirmationCode}</h1><p className="mt-4 text-stone-300">Tu horario fue reservado. Puedes pagar ahora de forma segura o pagar en sucursal segun la politica de la barberia.</p><button className="mt-7 rounded-full bg-amber-400 px-6 py-3 font-bold text-stone-950" onClick={pay} disabled={isSubmitting}>Ir a pagar con tarjeta</button></section></main>;
  if (hold) return <main className="flex min-h-screen items-center justify-center bg-stone-950 p-6 text-stone-100"><form onSubmit={confirm} className="w-full max-w-lg rounded-3xl border border-emerald-500/40 bg-stone-900 p-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Horario reservado</p><h1 className="mt-3 text-3xl font-bold">Completa tus datos</h1><p className="mt-3 text-stone-300">Expira: {new Date(hold.expiresAt).toLocaleString("es-MX")}</p><div className="mt-6 grid gap-3"><input className="rounded-xl bg-stone-800 p-3" name="name" placeholder="Nombre completo" required /><input className="rounded-xl bg-stone-800 p-3" name="phone" placeholder="Telefono" required /><input className="rounded-xl bg-stone-800 p-3" name="email" type="email" placeholder="Correo opcional" /><textarea className="rounded-xl bg-stone-800 p-3" name="notes" placeholder="Notas opcionales" /><button className="rounded-xl bg-amber-400 p-3 font-bold text-stone-950" disabled={isSubmitting}>Confirmar cita</button></div>{error && <p className="mt-4 text-red-300">{error}</p>}</form></main>;
  return <main className="flex min-h-screen justify-center bg-stone-950 px-4 py-10 text-stone-100"><section className="w-full max-w-2xl rounded-3xl border border-stone-800 bg-stone-900 p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-400">Reserva en linea</p><h1 className="mt-3 text-4xl font-bold">Agenda tu cita</h1><form className="mt-8 grid gap-5" onSubmit={reserve}><label>Sucursal<select className="mt-2 w-full rounded-xl bg-stone-800 p-3" value={branchId} onChange={(event) => { setBranchId(event.target.value); setServiceId(""); setBarberId(""); setSlots([]); setStartAt(""); }} required><option value="">Selecciona</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><label>Servicio<select className="mt-2 w-full rounded-xl bg-stone-800 p-3" value={serviceId} onChange={(event) => { setServiceId(event.target.value); setBarberId(""); setStartAt(""); }} required><option value="">Selecciona</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name} ({service.durationMinutes} min)</option>)}</select></label><label>Barbero<select className="mt-2 w-full rounded-xl bg-stone-800 p-3" value={barberId} onChange={(event) => { setBarberId(event.target.value); setStartAt(""); }} required><option value="">Selecciona</option>{barbers.map((barber) => <option key={barber.id} value={barber.id}>{barber.name}</option>)}</select></label>{barberId && <><fieldset><legend className="font-medium">Elige un dia</legend><div className="mt-2 grid grid-cols-3 gap-2 sm:grid-cols-5">{Array.from({ length: 10 }, (_, index) => dateValue(index)).map((item) => <button className={`rounded-lg border p-3 text-sm font-bold ${date === item ? "border-amber-400 bg-amber-400 text-stone-950" : "border-stone-700 bg-stone-800"}`} type="button" onClick={() => { setDate(item); setStartAt(""); }} key={item}>{dateLabel(item)}</button>)}</div></fieldset><fieldset><legend className="font-medium">Horarios disponibles</legend>{isLoadingSlots ? <p className="mt-3 text-sm text-stone-300">Buscando horarios...</p> : slots.length ? <div className="mt-2 grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map((slot) => <button className={`rounded-lg border p-3 font-bold ${startAt === slot.startAt ? "border-amber-400 bg-amber-400 text-stone-950" : "border-stone-700 bg-stone-800"}`} type="button" onClick={() => setStartAt(slot.startAt)} key={slot.startAt}>{timeLabel(slot.startAt)}</button>)}</div> : <p className="mt-3 rounded-lg bg-stone-800 p-3 text-sm text-stone-300">No hay horarios disponibles este dia. Elige otra fecha.</p>}</fieldset></>}<button className="rounded-xl bg-amber-400 p-3 font-bold text-stone-950 disabled:cursor-not-allowed disabled:opacity-50" disabled={isSubmitting || !startAt}>Reservar horario</button>{error && <p className="text-red-300">{error}</p>}</form></section></main>;
}
